### ISSUE TITLE
请问您网站上的鼠标拖尾是如何实现的

### ISSUE THREAD

**Issue by jizizr** [77mark/WakeHeroku#1]
请问您网站上的鼠标拖尾是如何实现的

**Comment by Ysnsn** [comment]
<script src="https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@latest/Hexo/js/mouse_snow.min.js"></script>
加进去就行了

**Comment by jizizr** [comment]
谢谢，还有其他的美化是怎么做的呢

**Comment by Ysnsn** [comment]
还有什么，

**Comment by jizizr** [comment]
文字，和评论区

**Comment by Ysnsn** [comment]
百度搜下就知道了
